version: 0.2

env:
  variables:
    SOLUTION_PATH: Allure.Net.Examples.sln
    BUILD_TFM: 'net6.0'
    BUILD_CONFIGURATION: 'Release'
    RESTORE_OUTPUT_PATH: 'packages'
    PROJECT_NAME: Dummy.App
  exported-variables:
    - DOTNET_FRAMEWORK
    - BUILD_CONFIGURATION
    - RESTORE_OUTPUT_PATH
    - PROJECT_NAME

phases:
  install:
    commands:
      - echo "Install .NET 6.0 LTS Release"
      - /usr/local/bin/dotnet-install.sh --channel LTS
  build:
    commands:
      - dotnet restore ./$PROJECT_NAME/$PROJECT_NAME.csproj --packages $RESTORE_OUTPUT_PATH -p:TargetFramework=$BUILD_TFM
      - dotnet build ./$PROJECT_NAME/$PROJECT_NAME.csproj --no-restore --framework $BUILD_TFM --configuration $BUILD_CONFIGURATION

artifacts:
  files:
    - $PROJECT_NAME
  base-directory: ./$PROJECT_NAME/bin/$BUILD_CONFIGURATION/$BUILD_TFM
