trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  BUILD_TFM: 'net6.0'
  BUILD_CONFIGURATION: 'Release'
  RESTORE_OUTPUT_PATH: 'packages'
  REPORTS_PATH: 'test-results'
  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
    packageType: 'sdk'
    performMultiLevelLookup: true

- task: Bash@3
  displayName: 'Install allurectl'
  inputs:
    targetType: 'inline'
    script: |
      wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl
      chmod +x ./allurectl
  
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '*Tests/*.csproj'
    restoreDirectory: '$(RESTORE_OUTPUT_PATH)'
    restoreArguments: ' --packages $(RESTORE_OUTPUT_PATH) -p:TargetFramework=($BUILD_TFM)'

- task: DotNetCoreCLI@2
  displayName: 'Build test projects'
  inputs:
    command: 'build'
    projects: '*Tests/*.csproj'
    arguments: ' --no-restore --framework $(BUILD_TFM) --configuration $(BUILD_CONFIGURATION)'
    restoreDirectory: '$(RESTORE_OUTPUT_PATH)'

- task: Bash@3
  displayName: 'Run tests'
  inputs:
    targetType: 'inline'
    script: |
      ./allurectl watch --results ./Allure.Net.Examples.xUnit.Tests/bin/$(BUILD_CONFIGURATION)/$(BUILD_TFM)/allure-results -- dotnet test ./Allure.Net.Examples.xUnit.Tests/Allure.Net.Examples.xUnit.Tests.csproj --no-restore --framework $BUILD_TFM --configuration $(BUILD_CONFIGURATION)
      ./allurectl watch --results ./Allure.Net.Examples.NUnit.Tests/bin/$(BUILD_CONFIGURATION)/$(BUILD_TFM)/allure-results -- dotnet test ./Allure.Net.Examples.NUnit.Tests/Allure.Net.Examples.NUnit.Tests.csproj --no-restore --framework $BUILD_TFM --configuration $(BUILD_CONFIGURATION)
  env:
    ALLURE_ENDPOINT: $(ALLURE_ENDPOINT)
    ALLURE_PROJECT_ID: $(ALLURE_PROJECT_ID)
    ALLURE_TOKEN: $(ALLURE_TOKEN)
